services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecocombustible-api
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 4000
      HOST: 0.0.0.0
      DATABASE_URL: postgresql://postgres:postgres@db:5432/ecocombustible
      JWT_SECRET: change_me
      PUBLIC_BASE_URL: http://localhost:4000
      FILES_BASE_URL: http://localhost:4000
      CORS_ORIGIN: http://localhost:19006,http://localhost:8081
      TRUST_PROXY: "false"
      RATE_LIMIT_MAX: 120
      RATE_LIMIT_WINDOW: "1 minute"
      EXPO_PUSH_URL: https://exp.host/--/api/v2/push/send
      REDIS_URL: redis://redis:6379
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
      - minio
    volumes:
      - ecocombustible-storage:/app/storage

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecocombustible-worker
    restart: unless-stopped
    command: ["npm", "run", "worker"]
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/ecocombustible
      JWT_SECRET: change_me
      PUBLIC_BASE_URL: http://localhost:4000
      FILES_BASE_URL: http://localhost:4000
      TRUST_PROXY: "false"
      RATE_LIMIT_MAX: 120
      RATE_LIMIT_WINDOW: "1 minute"
      EXPO_PUSH_URL: https://exp.host/--/api/v2/push/send
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
      - minio
    volumes:
      - ecocombustible-storage:/app/storage

  db:
    image: postgres:16
    container_name: ecocombustible-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecocombustible
    ports:
      - "5432:5432"
    volumes:
      - ecocombustible-db:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ecocombustible-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ecocombustible-redis:/data

  minio:
    image: minio/minio:latest
    container_name: ecocombustible-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ecocombustible-minio:/data
volumes:
  ecocombustible-db:
  ecocombustible-redis:
  ecocombustible-minio:
  ecocombustible-storage:
